title: 'Auth0 Blog'
description: 'Company Updates & Technology Articles'
url: 'https://auth0.com'
baseurl: '/blog'
markdown: rdiscount
paginate: 5
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, Rakefile]
permalink: /:title/
highlighter: pygments
excerpt_separator: '<!-- more -->'
encoding: utf-8
ampdir: 'amp'
is_non-tech: false
non-tech_dir: 'business'
tech_dir: 'tech'
only_first_p:
  show_read_more_link: true
  read_more_link_text: 'Read more'
stylus:
  compress: true
  path: ./css
values:
  is_post_index: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      design:
        image_default: https://cdn.auth0.com/styleguide/components/1.0.8/media/logos/img/badge.png
  -
    scope:
      path: ""
    values:
      related:
        - 2015-05-14-creating-your-first-real-world-angular-2-app-from-authentication-to-calling-an-api-and-everything-in-between
        - 2015-04-09-adding-authentication-to-your-react-flux-app
        - 2015-03-31-critical-vulnerabilities-in-json-web-token-libraries
